src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Float_;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Designation;

    /**
     * @return mixed
     */
    public function getDesignation()
    {
        return $this->Designation;
    }

    /**
     * @param mixed $Designation
     */
    public function setDesignation($Designation): void
    {
        $this->Designation = $Designation;
    }

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Quantite;

    /**
     * @ORM\Column(type="float")
     */
    private $Prix;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="produits")
     */
    private $categorie;

    /**
     * @ORM\ManyToOne(targetEntity=Produit::class, inversedBy="produits")
     */
    private $produit;

    /**
     * @ORM\OneToMany(targetEntity=Produit::class, mappedBy="produit")
     */
    private $produits;

    /**
     * @ORM\ManyToOne(targetEntity=Panier::class, inversedBy="produits")
     */
    private $panier;

    /**
     * @ORM\ManyToOne(targetEntity=Fournisseur::class, inversedBy="produits")
     */
    private $fournisseur;

    /**
     * @ORM\Column(type="guid", nullable=true)
     */
    private $Image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantite(): ?string
    {
        return $this->Quantite;
    }

    public function setQuantite(string $Quantite): self
    {
        $this->Quantite = $Quantite;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPrix()
    {
        return $this->Prix;
    }

    /**
     * @param mixed $Prix
     */
    public function setPrix($Prix): void
    {
        $this->Prix = $Prix;
    }



    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getProduit(): ?self
    {
        return $this->produit;
    }

    public function setProduit(?self $produit): self
    {
        $this->produit = $produit;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(self $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->setProduit($this);
        }

        return $this;
    }

    public function removeProduit(self $produit): self
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getProduit() === $this) {
                $produit->setProduit(null);
            }
        }

        return $this;
    }

    public function getPanier(): ?Panier
    {
        return $this->panier;
    }

    public function setPanier(?Panier $panier): self
    {
        $this->panier = $panier;

        return $this;
    }

    public function getFournisseur(): ?Fournisseur
    {
        return $this->fournisseur;
    }

    public function setFournisseur(?Fournisseur $fournisseur): self
    {
        $this->fournisseur = $fournisseur;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }


}

src/Controller/BackEvenementController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Form\EvenementType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BackEvenementController extends AbstractController
{
    /**
     * @Route("/back/evenement", name="back_evenement")
     * @param Request $request
     * @return Response
     */
    public function index(Request $request): Response
    {
        $evenement = new Evenement();
        $form= $this->createForm(EvenementType::class);
        return $this->render('back_evenement/index.html.twig', [
            "form"=>$form->createView()
        ]);
    }
}

templates/back_evenement/index.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Hello BackEvenementController!{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Ajouter un événement</h4>
            <p class="card-description"> Veuillez remplir les champs vides </p>
            {{ form_start(form) }}
            <form class="forms-sample">
                <div class="form-group">
                    <!-- <label for="exampleInputName1">Name</label>
                    <input type="text" class="form-control" id="exampleInputName1" placeholder="Name"> -->
                    {{ form_label (form.destination) }}
                    {{ form_widget (form.destination) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.description) }}
                    {{ form_widget (form.description) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.date) }}
                    {{ form_widget (form.date) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.prix) }}
                    {{ form_widget (form.prix) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.nbr_participants_max) }}
                    {{ form_widget (form.nbr_participants_max) }}
                </div>
                <div class="form-group">
                    {{ form_row (form.image) }}
                </div>


                <!--<div class="form-group">
                    <label for="exampleInputEmail3">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail3" placeholder="Email">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword4">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword4" placeholder="Password">
                </div>
                <div class="form-group">
                    <label for="exampleSelectGender">Gender</label>
                    <select class="form-control" id="exampleSelectGender">
                        <option>Male</option>
                        <option>Female</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>File upload</label>
                    <input type="file" name="img[]" class="file-upload-default">
                    <div class="input-group col-xs-12">
                        <input type="text" class="form-control file-upload-info" disabled="" placeholder="Upload Image">
                        <span class="input-group-append">
                            <button class="file-upload-browse btn btn-primary" type="button">Upload</button>
                          </span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="exampleInputCity1">City</label>
                    <input type="text" class="form-control" id="exampleInputCity1" placeholder="Location">
                </div>
                <div class="form-group">
                    <label for="exampleTextarea1">Textarea</label>
                    <textarea class="form-control" id="exampleTextarea1" rows="4"></textarea>
                </div>  -->
                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                <button class="btn btn-dark">Cancel</button>
            </form>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}